version: "3.5"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: gb/nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/data
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  php:
    container_name: php # имя контейнера после запуска
    hostname: php
    image: gb/php
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network



  cli:
    container_name: cli
    hostname: cli
    image: gb/cli
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data:/data

    networks:
      - app-network

networks:
  app-network:
    driver: bridge